/*-------------------------*\
|          Jour 24          |
\*-------------------------*/

var input = "swseeneeswneenwneenwswenenwnewswnesw;neneswnwnwnenenenwnenenenenenwne;sweseeseeeeenwe;wswseneeenweeeeeeneeeseeseswe;nwnwnwnenwnwnwswnwnwswnwnwnwnwnwnwnenwee;ewnenenwnwenenwswsesenenweseeew;seswseseseseswneswsesesesesew;enenwneeneswnwswneneneswseneeneneenwne;sewsesesenwseneswsesenenenewseseesesesesw;eswwseswnwsesenweswnweseswsewsesese;nwnwnwwnwnwswnwnwwnwnwswnwnweenwnww;sewwsenwwwnwnewwwwwwnewnwsenww;swswnwswneseswswseswswwswswnenesweseeswnw;wwwsewswswwswsweswswswnwnweneswsww;swwwwwwwswwswsweswsw;seseswwwswswswseneseswseesenwse;nweeneseswswswswweswswneswswswnewne;nweenwseeseeseeeseseswseeswseese;wwnwswewnesewwwwwwwwswwsww;wseseeweenwesesesewnweeseswesesee;seeswnenwewneeeeeswenwnewswnee;wneseswswseesenwswnwesweeeneeene;neswswseseswsesesenwseseseswseswesewsesw;nwnwnwnwnwnenwwnwsenesenwnwnwnwnwnwswnwnw;esewwnwnewseswwwweswwww;wnwnwnwwneenwnwnwnwnewnwsenwnwenw;wsewwwwnewswwwwwewwswnenesw;seseswwseseswsweswesweswnwnwswswwswse;nenwnwnwsenenenwnwnwnwnwnwnwnwnw;nenenenenenwnesenewnewnewneseeeene;swneswswseseswseseswswseswwesenwswswsesw;wsweswwneswwswwnwswsweswsewsesww;swswnewwswwswnwwnwswsesenwwewww;nwwnwenwnwwwswsewwnwwnwnwnwnwnw;wswnesenwnwwseweswnweseseseesenesese;seswswswseswseswswnwesesenwseswswswnwsw;eenenwesweeneswneswewenwenesene;nwswnwenesesesenwseseeeneeweseseswwse;esenenwnweswnewwswenenesewswseesw;wwwswnwwwsenenwsenweswwneswwwnww;wswswswenweweseswneswnwswwseeswnese;neswneenwseeswnwsewnewnwwwesww;enwnwwsenwnwenwwnwenwwwnwnwnwnenesw;seeeneeeneseeewsewseweweese;ewwwewwswswswswsewwwswwnwsww;neneseseneeneneeneeeenwwe;nwnenwneneenwnenenenwnwswnwswseenenenew;swnenwnwswnwswnwnenwnenwnwnwnwnwnwnwswnwne;eseseswswswnwswseseswseswswsenesenwseswse;enwswnenweseneeeeesenwsweeswee;seswnwnwnenwnwnwnwswnwne;swesewseeseeeseweweseeenweee;nwsewseseweneseseneseseseenwseswseseese;ewnenwswwwwwwwwwwnwsewwwwsew;neswnwnwswswswseseweseseseeseswswwswse;eswnwnwneseenenwwnwnwsenwwnwsenenwne;seenwseswswswnwseswsenwswswswswseseesw;seneswenewsesenwswnesewseeseneewsese;nweewswswnwseswsweneseseeswnw;neneswnenenwneesenwseneneewewneene;nenwnenwnwnwwneneneenene;seweswseseneswswsewswswseswnenene;sewnwswsenweseweswenewse;seseseseseeswseseswsenwsesenwseswsesese;eenenweeneeeseee;swseswseseswnenesesenwnwneseneswwwnwsw;swewnewwwweswwsewswwswswswsww;seswswswswneswswswsw;senwseswswnwswswswswwswwwswwswwswnee;seseswswseesewwneswseneseseswsweswsw;swwswwswswsewwswswwsenwneswswwsww;wwswswnwwewwwswswswwwewswww;nwnenenenenenenenwneswnenewsenenenenwne;neswweeeeneeseeneneeeweeene;swswwswswswsweswswswswswneswsw;seseseeseeeneeeewnwnweeewsweese;swswswswswseswsewseeswswswswnwneswswsw;neesewseneswswnwswneswnwswwnwwswswne;swneswnenenenwneenee;neeseewseeeewnweswnweeweewe;seseswseseswswnenwneswsenenewswseesesw;swnwnwenwnwnwswwneswnwnewnwnenwnwswnenwse;nwwswseneneeswneewswwsesesenw;nenenwnwnwswswneenwnwnenwnenwnenwnwsenwne;sewsewnwneseenwseewsesesesesewseesene;seeesenenwseseseseenwseseseweeswsewse;nweenesenwneeeneneeneeeswnenene;ewwwwwewwnwwwwewswswew;seeseswesesesenenwnwswseenwnwsweeswnw;eseswswseneeswnenwwseseseseseseneswsww;sewseseseeesenweenewseeeseswesese;swseseseseneesesesesewseseeweseesese;seseseesesenwsesenwswsesesesesesesesenesw;eweeeneneswswsewsenee;wswwnewwwwsenwwnewswwewwwww;wwwnwwwwwswenewwwwwwnwnwwse;seseswseseseseseseseesesesenwsenwsesese;seseesenwnenwnewswswneesewswsesw;swnwswwwswsweswwe;wwswenewnewnwswweeswwsewnwswww;nwwneswswswswsweswwswswnewswswswswswswsw;wseswnwneswseeseeeeneeeseseeseew;wwwsewwwewwnewwwwnwwwww;wswswswseeswnwswweseseweswswswswne;nwnwnwnwnwnwsenwnenewnwwwnwnwsewnwww;swswseneswswswswswswsewswswswnwnwe;enenwswswseswseseswswswseswswsenenwsw;nwswneswnenwswsenenweeswsesesewseswse;neesewsweswewseswseseseswseswnwnwswsenw;neeneneeneneneneneeseeneneswwwnee;nwswsewnwswswenesenwneneewseweenwnw;nwnwnewwwsewswseeswenwnwnenwnwneenww;wwewwwnwwwwsewwne;seswesenweswswnwswswswneenw;eeeneeenenewneneeneneenee;swswswnwewwnwwwseswswwswewnwwswswsw;wwwnwnwwwnwwesesewwe;swesesesenwsesesesenwseswseswswsese;nwnwsenwsenwenwnwnewnenwnwnwsenenenew;neenwnenesesewnwnewnenewnenenenesenwne;nwnwseneesenwwnwnwnwnwnwnwnesewsenww;swswneswwswswswwnwswsewswwenwseswsw;wswnwsweweswsenwnwnenwwesenwnenesenwe;nenenenenenwnenenewswnenenwneneseneswnee;seseseenwenewsesesesesesesese;newwneenwsweewnesenee;sewnwnewsewnwwnwnwnenwwwnwenwnw;senwwnenwneswnwnwswnenwnwswnwwnenwwnwnw;wwswneswnwnwwwwsenwnwenwenwwnw;eseswnwnwseswweeseswnenesenwsesesenw;swwseeswswwnewwseswswswneswswswnew;seswseswseswswnwnewswseswseswnewswsesw;seseswnwnwneswswenwnwswswswsewwwwsw;wwwwswswnewswnenwwswswnwewseswe;eeneeeneneneeneesw;sewnenwswswswwswswswseeswswswneswswsw;wneneswnenwswseeswnenenenwseneswnewnene;nwnenwnenenesenewneneneneenwne;swsenwsenwseewewswseeswseeseswswsw;seeseneenwseneseseseseswsesesesesesew;wseswswswwnwsweswwwswwwwwwnew;swswswseswneswswseswswswswswsenwseswnese;nwnewsewwnwnesweswewswnwseswe;weneswsweewswsenwnwnwnwsenwnwwwnw;nenenenwwsenenenesenenwnenenene;swwswenwswseswseswswseswseswswneswswsw;nesenenenwsenenenesenenenenenenenwnenenww;nenwnenwnwnwwsenwnwnenenwsenenenwnenenw;seswswneswseseswswseseswseseenwwwswnw;seswseseesenwnesewnwnweseswenwwswe;eneeesenwenwwsweeseeseseseeesenwsw;swswnwswswseseseeswseseseswsweseswnwsese;nesenenenewnenenee;nwnenwenenwnwnwnwnwnenwnwnwneneswnwswnw;nwnesweswnwnewnenesenweneneeeswnene;seseseseseseseneswseswsw;wwnwsenwnwseneswwnewnwswwnwseswwenw;nwnwwewswswnwnwwwnwnwwnwsenwwnwnwnwne;neeneneeeeswsweeeenesweneeene;swswswsewseswswswnenwsewseswswsesesee;nwenenwwneseswneneneenenewswwnesenw;seseseswseeseseeneseesesenewsenesesww;eeeeeseseesenwse;nwnwnwnwwnenwnenesenwnwnenwnwnw;swnwneswsweseswsesenwswswswswswseswseswsw;neenwseseseweseseseeeeeeeeswne;ewseneseweeewsesesewse;senenwswnwnwenwsesenwnwnenwnenwswnenwnwnw;wswswswsweswswseswswwswswwswswnenesw;nwswswnenwenenenwnwnenene;wnewnwswwwneswweewewswwnewsew;eewnesenewneeeneneeeswneneenee;swswswswswswswneswneswneswswswwswneswne;swsenwwwwnwwsenewenenwwnwwnwnwnwnw;swnwnwwwwwwwwwnwwnwnwwe;nweeneseweeswneewneneneneeneeene;neneseneeneneeeenwneeweseneewse;nwswseeswswswsesesenwswseswseseswswsesw;neeneneneneneneesewneswneeweneenenee;wswwswnwwwswswswsesw;eneneeweeeenenenene;wwwnewswwnewwwwsesewwwwenwse;nwnwsewnwnwnwnwnwnw;neswseswswseswswseswswseesenenwnenenwne;nweeweenwneesenwswseswenw;swnewswswswseeneeswnweenenenwnewnwsene;swneneenewnenewnenwswneneswneenenenesw;nwsenwsewnenwsenwnwnenwnwwswswnwnwnwnwnwe;wewnwewwwewwwnwwswwwswswwsw;nwwwwsenwwnenesenewswwswewwswwsw;esweeneeesweeeneseenwneneeneswe;ewswswwswwwswswwwww;wwwsesenenwnwnewwewsewwswweswnew;nwneswnesenwneneesenwnwnenenwnewsenwnw;wsenenwnwnwseewsenwnwenweneswneseswwnw;swswswswseseswsenwsesweseesesesewswsw;eweeseesweneseeseesesesee;nwewseneswsewsenweseeseswsesenenenw;sesenwwswseeeeseeseseswneseseeesese;nenewneneneneneneneneenenwnwnesenenenesw;swseseeseseseseseseseesenwwswneese;seseseseseseseeeeseeseneseeweswnw;nwswwseneenewsesenenenwnenwsenesenwswnwe;nwnenwwsenwswewsenwnwnwnenwnwnwnwnwnwnwnw;sewswsweweswnwwneneswnese;nwswneseswseswseseseseswenwswswswswswswse;newenwnwswnwswnwnwneeswweswnwesenwsw;eenweeeeenwsenweseeeesewse;wseeeswswwwwwswsesenenenwswnwwwenw;eseeneenenweeesweeenwee;seswswswwseesesese;eeseseeeenwswnwseneseweseeeeseesw;seseseeseeneewwseswneseseneneswnwwe;wwwwwwwnewwwwseww;wseenwnwnwwsenwnewnwwwwweewsww;swwenwwwenwnwneseswesewwneswswse;swswnenenenenenenwnene;nwswneswwnwwswwsewsewnenwwwwenenw;nwswseseseeseswnweseswswseswswnwsesew;swnwswswsesenwsweseswsenwne;eneeneeneeeseeneneswswsweneenenewe;wsesweseswnweeeeeeenwesweenwe;nenenwwnweenenewneseneneswnwnenwswne;wwwweswwseswneswswnwwswneseswswswsw;eswenweseeeeeeweseneeneeseseee;seseseswseseneesesenwswsesesesesesesew;swswneseswswswseneswwwsesweseseseswse;weseeeseeeeeseseeneseeenwseswse;eseeneesenesewnesewseseswseseseesew;nwswswseswseseseseswseeeseneswswsewse;wnwnwsenenwnwsesenwwesewnenwseeswenenw;senweeseswwswseseseeneeese;neswseseseseseesesesesesesese;senwenwnwsweeswswseseseseeseneseeewse;eswnwswswseswsweswnwswnwwswnwswswsesw;seweswswsenwsenwseswsenesw;neneeneswnwnenenenwewnwnewneeswnwne;wswswswsenenwnwswswsweswswneneeswsesww;swnwnenwnenwnenenesesenenenenenenenwnene;enesweeenwswswnesweneneeneeeswee;nwnwnwsenwnwnwewnwnwnwnwnwnwneswnwnwnwnw;enwnesesewesenweseeewseenwesee;swsenewenesewwswwwsewnesw;eneeeneeeeeenwwneneeseeeewse;ewseeeenwnesewesweeeeeeseseee;nwwneneseswnenwnwnesesenesenenwnwswnwwne;eenwnwwwsewwwne;swenwnwnwnwnwewnwewnwswnwnwnwnwwnww;seesewseseswnesenwesenweeswswseswne;wwwweneneewseswsenwwswwwwwnew;enwnwnwwewseswwnwwnwnwnwwnwnwwee;enenenenenwnenenwwnwnenenwswneneenenw;eeweseeewseeesesweeenenwenesese;neswnwneneneneeneeeneneeneeneswnene;swwswwswewwswwswswwneswswwswsesw;neswneneseneneneneneneneneneneneswnwnenene;nwwnwnewnenweswnwweswseenwsewwnwse;eseeeweeeseeeenwswesenweeee;seswseseswswneseneseseseseswseseseseenenw;neseewswswweweeewwenwewsenwnw;seswnwseseseeesenwwseseseswnesesesese;swwnwswnwnwnwwnwnwnwenwenwnwnwnwnwnw;eneseneswewneseenwenwnweseneeneenw;swsenwwwseswswnwswswwenwswswsweswsw;neneneneneneenenewneseeneenenwswene;swswswswswswwswswenwwswswswswswswswe;swnwswwnenwswwneeseseswwnenesewsene;neeesweewneenwneseeeeneeenee;wnwwwswnwnewswnwswsewnwnenweeswnew;swneneneneneeneneeeneneeswnenene;weseswseeswewnwwseseese;eesweeseeeseeeenweee;seswswwsewseswneneswwwneswneewneswww;sewseswsewswwswwwwnwnesweswnwneswe;nwnwnenewnwnenwsenenenwneenwnwnesewnene;swnwswnwnwswesenesesesewnwsenwnwneese;wnwnwwnwwnwnwwenwnwnwenwwwnwseew;nesweseswwnwnwnwnwwswswseenenwwsesw;esesenwneneeneneseneeenewewe;wsesweswnwswneswswswwsesenwswneswswsw;eswnenwenenwneeeswewenweneeesw;wneneeneeswneenenenewneneenenenenwnese;wwnwwwsewnwwwwnenewsenwwwww;nwsenwsenwnwnenwnwwnwnwneswneneneenenwnene;wswnweneswswesweeewwnenwnenwnenwne;wewwwwwnwswwnenwnewswwewswnw;swwwnwweeswewswwwwsewwwnwnw;neeneeeenwneneeweneeseee;swenwneeneswneneewneneeneseseeswew;nweeeeeeseeeeeeswesweeene;nwnwenwnwneseneseswnwnewenwswnwenewnw;wsesesesesesesesesesenesesw;wwwwwnewweswswnwwewwewwsww;wnenwnwwwwwwnwnwwnwwnwnwsew;nwnenesenenenenenewneneweneneneenwnesw;esewnesenwneeswenenewswswwnwsesenwnw;eeeeeeeeeseneewswnweeeneswe;neneseseweswwwwswnwwswnwwsweswwww;seswswneswswswnewsweswswswsenenwwwsw;nenenweneneneneneswneneneeene;sewnwseeneseseeswseeenwseseseneseswee;enewneseeeseneeeeeneeeeneenew;esewswenweseenwseeeeeeesenesw;nwnwenwnwnwewnwswnwswseseneewnw;enwnwnenwnwwswnwnwnenwnwnenwnwsenenenw;nwsenwwnwenwenwnwwenwewswwenwww;senwsesesesesesenenwsesenwsenwneseseww;wsenwswseseswewswneseswswswesw;nwwnewwnwsewwwwwwsewwnwwseww;wsenesesenenwneswwseswswswneneswswseswsw;seseseseseseneseenwsesewseseseesesese;neneenenewnenenenenenenewneneenesew;ewwneswswnenenwswnwswseseeswnwesewsw;seswswewneswwnwnwnwswneneeseswnewe;nenwwnwwsenwswnwnwnwwnwwenwnwnwnwnwnw;wwwnwnwseswwnwwnwneeswwnwneswnwnw;swswwwnwnewwwweswswswwwwsewswsw;eeeeswesweeeeenweeenweenee;senwseweswnwnwswnenenwwnwsenwnwnenenw;nwnwwnwnwsesenwnwnwnwnwnwnwneswe;swseeseswseseseswneseswnwnwwseswnwsenw;nwwewewwnenwnweswsesee;swewwwsewwswswwnwwwswswnw;wnwweenewnwnwsweswwewwsewswse;swenesewsesewsesenesesewsenwesesewnw;eseseeeesenwesenweseseseseswswesese;nwnwnwnwnwnwnwnwnwnwsenwnwwnwnwnwnwsesenw;seeseenwnwwseneswseseseseswsesenwsee;swswswsweswwwswswnwswwswswswwswese;wswwwwnewwnwwswswwnwwsewsesewne;swswnwswneswenwswseswseseneseswwesww;swswneswswswswewswnwswww;nwnwnwnwnenwwnwenwnwnwnwnwnwnwnwseesw;swnwseneenenwneneseneneneeeenewnene;neeeeeseneneneneeeswnwneeswenene;enwwnwnwwnenwnwnwenwwnenwneesenwnene;nwwnenwenwewwesenwnwwswnwwsenww;wnwnwnwnwnwwnwnwswwnwenwnw;swwwwnewswnenwswseseswswnewesewne;nenwwnwnwnwnwnwneenwnwsenwnenwnwswnwnenw;neewsweeeeeeneeeeneeswneeee;wwswwwwseswswswwwswwwwnewwe;nwwswseneenesewswneswswneseswswwnesw;eneneneneneneenewnenenene;nwenwneneeeswwneeneswneneneseneeene;nenweeneenwnesewneswswenew;swwwweswnwwsweswswswwswswswwwsw;swswnwnwswswswswswswseswsweswswwswswsw;nesewswswseswseseneseneseseene;newneswwneeneeenenwswseneeenenwene;neneswseenenewneswwnenweenenenenwsene;seneneneseneswnwnenewenenenenwwswnenw;nwnwsenwnwnwnwnwsenesenwenwwnwnwswnewnwnw;seeesenesenwseeswwswnwnwseneseewenw;swswsesesenweseeseswwsesesenesenwsesesw;swswwneneswswswsweswswswswswswswswswswsw;wseseswneseseseseseseswneswesenwsesese;nwenwneeneseswswwnwnwnwnwwsewswnwne;nwnenenwwneseneenwnwnenwnwnenewne;sesenwseswenweeeeesesesesewsesesee;wnwswnenwwwenwwnwnenwwnwwsewwsww;nenenwnwnenwwnenwnenwwsenwnenwnwsenwewse";
var instructions = input.split(";");

var blackTiles = new Set();
for (var instruction of instructions) {
	var target = resolve(instruction);
	if (blackTiles.has(target)) {
		blackTiles.delete(target);
	}
	else {
		blackTiles.add(target);
	}
}
console.log("Phase 1: " + blackTiles.size);

function resolve(path) {
	var coords = [0, 0];
	
	while (path.length > 0) {
		var nextDir = path.match(/^(e|w|ne|nw|se|sw)/)[1];
		path = path.substr(nextDir.length);
		
		switch(nextDir) {
			case "e":
				coords[0] += 2; break;
			case "w":
				coords[0] -= 2; break;
			case "nw":
				coords[0] -= 1;
				coords[1] -= 1;	break;
			case "sw":
				coords[0] -= 1;
				coords[1] += 1;	break;
			case "ne":
				coords[0] += 1;
				coords[1] -= 1; break;
			case "se":
				coords[0] += 1;
				coords[1] += 1;	break;
		}
	}
	
	return coords.join("¤");
}

// part 2

for (var d = 1; d <= 100; ++d) {
	day();
}
console.log("Phase 2: " + blackTiles.size);

function day() {
	var nextGrid = new Set(), candidates = new Set();
	var directions = [
		[2, 0],// E
		[1, 1],// SE
		[-1, 1],// SW
		[-2, 0],// W
		[-1, -1],// NW
		[1, -1],// NE
	];

	for (var tile of blackTiles) {
		var coords = tile.split("¤");
		var nbWhites = 0;
		for (var direction of directions) {
			var candidate = [
				+coords[0] + direction[0],
				+coords[1] + direction[1],
			].join("¤");
			if (!blackTiles.has(candidate)) {
				candidates.add(candidate);
				nbWhites++;
			}
		}
		if (nbWhites == 5 || nbWhites == 4) {
			nextGrid.add(tile);
		}
	}
	
	for (var candidate of candidates) {
		var coords = candidate.split("¤");
		var nbBlacks = 0;
		for (var direction of directions) {
			var neighbour = [
				+coords[0] + direction[0],
				+coords[1] + direction[1],
			].join("¤");
			if (blackTiles.has(neighbour)) {
				nbBlacks++;
			}
		}
		if (nbBlacks == 2) {
			nextGrid.add(candidate);
		}
	}
	
	blackTiles = nextGrid;
}